-- 已废弃的系统角色 PROJECT_OWNER / PROJECT_EDITOR / PROJECT_VIEWER 统一迁移为 USER
-- （PROJECT_AUDITOR 已在 V9 迁移为 AUDITOR）
UPDATE sys_user SET role_code = 'USER' WHERE role_code IN ('PROJECT_OWNER', 'PROJECT_EDITOR', 'PROJECT_VIEWER');
